### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by kyzn** [kyzn/Dist-Zilla-Plugin-ContributorCovenant#3]
# TODO
- [ ] Rename to be more generic
- [ ] Add following
  - [ ]  [Geek Feminism](http://geekfeminism.wikia.com/wiki/Community_anti-harassment/Policy) (Public License)
  - [ ]  [Citizen Code of Conduct](http://citizencodeofconduct.org/) (CC BY-SA 3.0)
  - [ ] [Ruby Code of Conduct](https://www.ruby-lang.org/en/conduct/)
  - [ ]  [Technology Transformation Service](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md) (CC0 1.0 Universal)
  - [ ] [perlpolicy](https://metacpan.org/pod/perlpolicy#STANDARDS-OF-CONDUCT) (Artistic License or GNU GPL)
    - [ ] [Dancer](https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Policy.pod#STANDARDS-OF-CONDUCT) (same terms as the Perl 5)
  - [ ] [Mojolicious](https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Contributing.pod#CODE-OF-CONDUCT) (Artistic License 2.0)
  - [ ] [Django](https://www.djangoproject.com/conduct/) (CC BY 3.0)
  - [ ] [The Perl Conference](https://perlconference.us/tpc-2018-slc/standards-of-conduct/) (CC BY-SA 3.0)
    - including both SoC *and* handling SoC incidents
  - [ ] [No Code of Conduct](http://nocodeofconduct.com/) (CC BY-SA 3.0)

- [ ] Put all license templates in a nicely structured folder, don't keep them in perl files
- [ ] Accept following arguments at dist.ini
  - [ ] License name
      - [ ] Default to Geek Feminism
  - [ ] Template variables (such as email address, community name).
    - [ ] Default to whatever-information-is-available at dist.ini
    - [ ] If none available, put generic terms such as "This community" and "Bug Tracker"
  - [ ] Filename
    - [ ] Default to "CODE_OF_CONDUCT.md"
  - [ ] Location of code of conduct file
    - [ ] Default to "both repository and build"

# To follow up
- [FreeBSD](https://www.freebsd.org/internal/code-of-conduct.html), [irc.perl.org](http://www.irc.perl.org/rules.html), [Ruby](https://www.ruby-lang.org/en/conduct/) don't specify licenses.
- In addition to having the IRC SOC, is it ok if we clip "community policies" and "reasonable person principle" sections under a new name as "irc.perl.org-community"?

# Future
- Accept additional sections to document from dist.ini. This can be a text directly input to dist.ini, or it can be path to a markdown file to be consumed.
- Translations. I'll structure the directories to make this easy.
- Plugin model. (being able to mix and match to produce your own Standards of Conduct)

# More references
Click [here](http://geekfeminism.wikia.com/wiki/Code_of_conduct_evaluations) to see a list of most common Code of Conduct documents.

# Thanks
I gave a lightning talk on ContributorCovenant and this very module during last day of The Perl Conference in Glasgow, 2018. I've received a lot of ideas through discussions. I would like to thank mst, Finn, Larry, Gloria, Ruthie and Joelle for their ideas and support. Cheers! 🎉

**Comment by kyzn** [comment]
Since it's been a while, I should refresh the list of CoCs from above. Also add:

https://us.pycon.org/2019/about/code-of-conduct/

**Comment by kyzn** [comment]
Since "v2" is already released, I'm now considering releasing this roadmap as a new module.
